# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subitem',
            old_name='sub_item',
            new_name='main_parent',
        ),
    ]
